Repository 2023-D-coding-1th-TeamProject/Celebrem_frontend, pull requests merged in 2023-08, with the labels that each got.

#2 [Chore] 프로젝트 초기 세팅 및 eslint/prettier 설정
  frontend/src/App.js
  frontend/src/apis/axiosInstance.js
  frontend/src/assets/logo.svg
  frontend/src/components/common/Header/Header.jsx
  frontend/src/components/common/Input/Input.jsx
  frontend/src/index.js
  frontend/src/pages/LoginPage/LoginPage.jsx
  frontend/src/routes/Router.js
  frontend/src/styles/Reset.js
Labels: ⚙️ chore

#6 [Feature] Header 공통 UI 컴포넌트 구현
  src/components/common/Header/Header.jsx
  src/components/common/Header/HeaderStyle.jsx
  src/components/common/Search/Search.jsx
  src/components/common/Search/SearchStyle.jsx
  src/pages/HomePage/HomePage.jsx
  src/pages/SignupPage/SignupPage.jsx
Labels: ✨ feat, 🎨 UI

#9 [style] 캐러셀 공통 UI 컴포넌트 구현
  src/assets/icons/icon-carousel-left-arrow.svg
  src/assets/icons/icon-carousel-right-arrow.svg
  src/assets/images/carousel-img-01.jpg
  src/assets/images/carousel-img-02.jpg
  src/assets/images/carousel-img-03.jpg
  src/assets/images/carousel-img-04.jpg
  src/components/common/Carousel/Carousel.jsx
  src/components/common/Carousel/CarouselStyle.jsx
  src/pages/HomePage/HomePage.jsx
  src/styles/Theme.js
Labels: ✨ feat, 🎨 UI

#14 [style] Navbar 공통 UI 컴포넌트 구현 (#10)
  src/components/common/Navbar/Navbar.jsx
  src/components/common/Navbar/NavbarStyle.jsx
  src/layout/ContentsLayout.jsx
Labels: ✨ feature, 🎨 HTML/CSS

#17 [feature] 회원 정보 및 회원 정보 수정 페이지 마크업
  src/pages/AccountPage/AccountEdit/AccountEditPage.jsx
  src/pages/AccountPage/AccountPage.css
  src/pages/AccountPage/AccountPage.jsx
  src/pages/AccountPage/AccountPageStyle.jsx
Labels: ✨ feature, 🎨 HTML/CSS

#19 [feature] 인플루언서 등록 페이지 마크업
  src/components/common/Tags/CheckTags.jsx
  src/pages/RegisterPage/RegisterPage.jsx
  src/pages/RegisterPage/RegisterPageStyle.jsx
Labels: ✨ feature, 🎨 HTML/CSS

#20 [Feature, Style] 태그 컴포넌트화 (버튼, 체크박스, 프로필) 및 mock data 형성 및 호출
  package.json
  public/mockServiceWorker.js
  src/components/UserList/InfluencerList.jsx
  src/components/UserList/InfluencerListStyle.jsx
  src/components/common/Tags/MainTags.jsx
  src/components/common/Tags/ProfileTags.jsx
  src/constants/CategoryTag.jsx
  src/index.js
  src/mocks/browser.js
  src/mocks/handlers.js
  src/mocks/userData.json
  src/pages/HomePage/HomePage.jsx
  yarn.lock
Labels: ✨ feature, 🎨 HTML/CSS

#24 [Feature] 로그인, 회원가입 api 연결
  src/pages/LoginPage/LoginPage.jsx
  src/pages/SignupPage/SignupPage.jsx
Labels: ✨ feature, 👩‍💻 frontend

#28 [Feature] 상태 관리 recoil 설치 및 세팅, 헤더 atom 적용
  .env
  package.json
  src/atoms/userAtom.jsx
  src/components/common/Header/Header.jsx
  src/index.js
  yarn.lock
Labels: ⚙️ chore, ✨ feature, 👩‍💻 frontend

#26 [Feature] api 모듈화 및 로그인 페이지 연결
  .eslintrc.js
  .gitignore
  src/apis/auth.js
  src/apis/axiosInstance.js
  src/atoms/userAtom.jsx
  src/components/common/Button/Button.jsx
  src/components/common/Carousel/Carousel.jsx
  src/components/common/Input/Input.jsx
  src/pages/LoginPage/LoginPage.jsx
  src/pages/LoginPage/LoginPageStyle.jsx
  src/pages/SignupPage/SignupPage.jsx
  src/pages/SignupPage/SignupPageStyle.jsx
Labels: ✨ feature, 👩‍💻 frontend

#31 feature/인증코드모달창 #30
  src/components/common/Modal/Modal.jsx
  src/components/common/Modal/ModalStyle.jsx
  src/pages/SignupPage/SignupPage.jsx
Labels: ✨ feature, 🎨 HTML/CSS, 👩‍💻 frontend
